- docs/documentation/overview.md
noticed that the link to the document project settings in the third paragraph was a dead link so I've hopefully put the correct url in
> fixes broken project settings link

- docs/components/variants.md
Formerly "variants do no need to", should read "variants do not need to".
Love the project!
> Word change in variants.md

- .gitignore
- package.json
Suggestion for keeping track of code coverage via istanbul – in this changeset, coverage will be regenerated any time `npm test` is executed.
> add coverage reporting via istanbul

- test/core.mixins.collection.js
just testing the waters here – wanted to help increase test coverage and this is the first one that I came across that felt like low-hanging fruit.
> add missing test (collection items should call their `.toJSON`)

- .gitignore
- src/web/server.js
* const `watchers` is reassigned on `destroy`, changed to let
* added browsersync error handler, and bs handler
* removed duplicated `browser` prop from browsersync defaults
* `proxy` default prop should be an object for better defaults merging
* added `server` default for more readability, note that you can define only one property `proxy` or `server`, defining both will throw an error.
> Better BrowserSync support

- packages/internals/loader/README.md
- packages/internals/loader/index.js
- packages/internals/loader/index.test.js
- packages/internals/loader/package.json
- packages/internals/loader/src/loader.js
- packages/internals/loader/src/loader.test.js
- yarn.lock
A small wrapper class for Webpack's `enhanced-resolve` that provides support for requiring and resolving modules against a set of path aliases. It will be used to enable path-independent requiring of local modules in Fractal config files (for example, shared data files).
> Add alias-able module loader class

- packages/internals/support/src/collection.js
- packages/internals/support/src/collection.test.js
- packages/internals/support/src/component-collection.js
- packages/internals/support/src/component-collection.test.js
- packages/internals/support/src/component.js
- packages/internals/support/src/component.test.js
- packages/internals/support/src/entity.js
- packages/internals/support/src/entity.test.js
- packages/internals/support/src/file-collection.js
- packages/internals/support/src/file-collection.test.js
- packages/internals/support/src/file.js
- packages/internals/support/src/variant.js
- packages/internals/support/src/variant.test.js
This eliminates redundant properties and sets defaults if not provided.
Additionally, 
- add better validation for Collection classes, and 
- add [Symbol.toStringTag] references for testing and stack traces
> Improve and simplify Component class construction

- packages/internals/support/index.js
- packages/internals/support/index.test.js
- packages/internals/support/src/collection.test.js
- packages/internals/support/src/component-collection.test.js
- packages/internals/support/src/component.test.js
- packages/internals/support/src/emitting-promise.js
- packages/internals/support/src/emitting-promise.test.js
- packages/internals/support/src/entity.test.js
- packages/internals/support/src/file-collection.test.js
Ensure EmittingPromise is exported, and add some fixes to [Symbol.toStringTag] false positive tests
> Ensure EmittingPromise is exported

- packages/internals/parser/test/helpers.js
- packages/internals/support/src/collections/collection.js
- packages/internals/support/src/collections/collection.test.js
- packages/internals/support/src/collections/component-collection.js
- packages/internals/support/src/collections/entity-collection.js
- packages/internals/support/src/collections/file-collection.js
- packages/internals/support/src/collections/variant-collection.js
- packages/internals/support/src/entities/entity.js
- packages/internals/support/test/collection-maps.test.js
Enable automatic mapping of Collections to the correct type, based on the return type of the supplied map function
> Add entity mapping

- packages/fractal/fractal-transform-components/src/transform.js
- packages/fractal/fractal-transform-components/src/transform.test.js
- packages/fractal/fractal/src/config/defaults.js
- packages/fractal/fractal/src/config/schema.js
- packages/internals/support/src/collections/collection.test.js
- packages/internals/support/src/collections/file-collection.js
- packages/internals/support/src/collections/file-collection.test.js
- packages/internals/utils/src/utils.js
- packages/internals/utils/src/utils.test.js
- Overload the `FileCollection.filter()` method (and corresponding `.reject` method) to filter by path if a string or array is passed as the sole argument 
- Reworks the main fractal config structure to nest component config properties under the components key
- Change `filter` property names to `match` in config
- Use glob strings in default app config for matching component views and config files
- Use defaultsDeep for merging global config defaults with the component configuration
> Component config handling improvements

- package-lock.json
- package.json
Addressing the security vulnerability in #461:
- Updates mocha to 4.0.1 to remove growl@1.9.2. 
See https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#401--2017-10-05.
- Update vorpal to 1.12.0 after npm audit found additional errors. 
Tested on 
- macOS 10.12.6
Node versions: 
- v6.9.4
- v8.11.4 
- v10.9.0
> Update mocha and vorpal

- src/core/resolver.js
This PR fixes the issue where setting a context var's value to `0` or `false`, it is incorrectly converted to `null`.
foo.config.json
```json
{
"context": {
"foo": 0,
"bar": false
}
}
```
renders as:
```json
{
"foo": null,
"bar": null
}
```
> Don't return null for falsey context values. Fixes #400

- src/core/markdown.js
- test/core.markdown.js
This PR should address #464 as well as frctl/nunjucks#5. The circular reference issue was caused by the markdown renderer directly mutating its supplied config object, which itself (as part of the complete fractal config object) is later made available to templates as a property of the _env variable.
A basic test has been included to confirm the md config object is now cloned before mutation. If anyone is still having issues after this fix then let me know :-)
> Circular reference fix

- src/core/data.js
There is currently no notification when `readFile` fails to load a file. Can easily happen when a file is moved, renamed and deleted.
> Log Error when readFile fails to load a file

- .snyk
- package-lock.json
- package.json
Supersedes changes made by #480. Regenerates the `package-lock.json` file
> fix: upgrade away vulns where possible

- README.md
A first pass at adding a Contributing section to the README and removing the project status notice, as suggested by @Chapabu on the Fractal Slack workspace.
Any improvements/iterations on the wording much appreciated.
> Remove project status note, add Contributing section

- src/web/server.js
This PR adds a name to the browser-sync instance that gets created equal to the name of the project. This allows other files (gulp, webpack, etc.) to access the Fractal instance directly and trigger reloads and other browser-sync API events.
Once the Fractal server is running, other files can access the instance via browser-syncs `.get` api:
```javascript
// gulpfile.js, etc.
const syncServer = require('browsersync').get('Project Name');
```
Merging this could close #501
> Add project title as named browser-sync instance

- src/core/data.js
This solves the problem described in https://github.com/frctl/fractal/issues/417.
When using Fractal with JS-based config files (`*.config.js`), BrowserSync will crash and not recover if the config file has a syntax error in it. Even after fixing the syntax error, the browser will refresh, but still shows the last state of the component before the error occurred. It never reflects the new, valid state of the configuration. The only remedy is then to restart the Fractal server.
**Steps to reproduce:**
1. Create a Fractal project using the "TL;DR method" described [here](https://fractal.build/guide/getting-started.html#the-tl-dr-method).
2. Switch the `example.config.yml` file to `example.config.js`, while updating the syntax appropriately (you may need to restart the Fractal server after …
> Fixed sync crash when JS config files contain errors. (#417)

- src/cli/commands/web.start.js
as described in issue https://github.com/frctl/fractal/issues/514
current handling 404 errors as working since latest release cause the fractal dev server to stop.
**Technical scenario description**:
in _onrequest, the lack of a match creates a web error, and pushes it to the next middleware layer:
` src/web/server.js:214
return next(new WebError(404, `No matching route found for ${req.path}`));
`
this is pushed to the _onError middleware layer, which emit an error event on the server object
` src/web/server.js:257
this.emit('error', err, res.locals.__request);
`
this error event is caught in the dev server vorpal command, which as of latest release, calls done()
` src/cli/commands/web.start.js:41
done();
`
which stops the dev server.
> prevent 404 errors from stoppping fractal server

- src/fractal.js
It can be pretty useful to communicate warnings and such in context:
```javascript
const { log } = require("@fractal/fractal");
log.warn("Deprecated: this context-data should not be used anymore - Use ... instead.");
```
> Export Log for usage in context

- package-lock.json
- package.json
This saves 46M for package users.
```
~/tmp/fractal-webpack-boilerplate (master)
rachman@quark $ du -hs node_modules/
238M	node_modules/
~/tmp/fractal-webpack-boilerplate (master)
rachman@quark $ du -hs node_modules/
192M	node_modules/
```
> Move snyk to devDependencies

- src/web/server.js
Removes `.end()` since `.send()` already handles this:
> "Use to quickly end the response without any data. If you need to respond with data, instead use methods such as res.send() and res.json()." - https://expressjs.com/en/4x/api.html#res.end 
Will hopefully address some occasional failed responses. See #545 for context.
> Remove end from server rendering

- src/api/components/source.js
This PR will resolve #556.
Following this change, we will allow users to exclude some directories from Fractal structure like so:
```js
fractal.components.set('exclude', '**/node_modules/**');
```
... or an array of exclusions:
```js
fractal.components.set('exclude', ['**/node_modules/**', '**/tests/**']);
```
Filed a docs issue as well: frctl/fractal-docs#40
> add exclude config option to components

- src/core/utils.js
Resolves #522.
Quoting my comment from the issue:
> In order to get the correct URLs, you should use the path helper that's been provided by most official adapters. For example, with the default handlebars adapter, [Change Log]({{path './change_log'}}) should do the trick.
>
> However, the core utility function that the path helpers in adapters use, returns early for relative paths. This is a bug, since even relative paths should be appended with the proper file extension.
Basically currently there's a difference how `{{path 'change_log' }}` and `{{path './change_log' }}` work, even though they really point to the same relative path.
> append extension to relative URLs too

- package-lock.json
- package.json
the pretest command in symlink-dir basically self-requires the package to make the tests succeed. without it, in the context of this repository, mandelbrot can't require `@frctl/fractal` since it does not exist in node_modules anymore. not sure if this is the best or even correct solution, but it seems to work for now.
> update handlebars adapter

- src/core/resolver.js
Currently you can only reference and render context items contained within sub-components (e.g. `@menulocaltask.link`). Referencing `@menulocaltask` causes `[object Object]` to be rendered. This pull request adds the ability to reference `@@menulocaltask`, which will enable it to render the full component when no sub-context is specified with dot notation.
This is useful for template engines/styleguides which can't use partials to include other components. For example, Drupal's theming system can have other partials represented as regular twig variables.
Example:
```
label: "Menu Local Tasks"
context:
primaryTabsTitle: "Primary Tabs"
primary:
- "@@menulocaltask"
- "@@menulocaltask--active"
```
> Allow sub-components to be rendered fully

- src/core/markdown.js
This will partially resolve #484.
Without the hljs class, only the contents of the code blocks are styled according to the highlight.js theme. If the user tries to customize the highlight.js theme (for example, use a dark theme), the background is provided by mandelbrot and might not match the hljs theme background.
This needs frctl/mandelbrot#105 as well.
> add hljs class to code elements

- src/core/resolver.js
Resolves #455 
Now, when using:
```yaml
context:
date: 2020-01-01
```
it will be resolved to `2020-01-01T00:00:00.000Z`.
We could also resolve it to string (`Wed Jan 01 2020 02:00:00 GMT+0200 (GMT+02:00)`), but I think ISO timestamp is more correct in this case. I believe everything else in context is resolved to JSON as well in the end.
> resolve date in config to JSON string

- package-lock.json
- package.json
- src/core/fs.js
Fixes #588
It's a major bump but according to [their changelog](https://github.com/bevry/istextorbinary/blob/master/HISTORY.md#v300-2019-november-18), it's because of the drop of Node versions below 8, which we already doesn't support anymore.
> chore: update istextorbinary to get newer extensions

- packages/fractal/bin/fractal.js
- packages/fractal/package.json
Since the bin file did not have a js extension, it was not linted/formatted in #612. This also means that it currently bypasses all import lint rules that are rather important.
Looking at the JS ecosystem, it seems fairly common that the bin file is a JS file, so I'm fairly comfortable changing this.
> refactor: change bin file to js & lint/format

- packages/mandelbrot/assets/scss/components/_pen.scss
- packages/mandelbrot/assets/scss/components/_preview.scss
Resolves #610.
I opted to use the same functionality we have on larger screens - pen preview resizing. I tested it and it seemed to work fine on touch screens as well. I made the handle a bit larger, though, to make it easier to target with fingers. If users want the preview to take up 100% height (like it has been so far), now they need to drag the handle to the bottom of their screen.
> feat: allow resizing pen preview height on narrow screens

- packages/fractal/config.js
- packages/web/src/engine/filters/highlight.js
Resolves #582.
For example, adding svelte language support:
```js
const hljs = require('highlight.js');
const hljs_svelte = require('highlightjs-svelte');
const _ = require('lodash');
hljs_svelte(hljs);
fractal.web.set('highlighter', function (content, lang) {
content = _.toString(content || '');
lang = lang ? lang.toLowerCase() : lang;
try {
return lang ? hljs.highlight(lang, content).value : hljs.highlightAuto(content).value;
} catch (e) {
return hljs.highlightAuto(content).value;
}
});
```
I thought about just allowing passing in an extended HighlightJS, but this would be more dynamic - it would allow to use some other highlighting lib if necessary.
Needs documenting after merge.
> feat: allow overriding/extending highlighter

- packages/mandelbrot/assets/scss/components/_asset-list.scss
- packages/mandelbrot/assets/scss/components/_browser.scss
- packages/mandelbrot/assets/scss/components/_file-browser.scss
- packages/mandelbrot/assets/scss/components/_header.scss
- packages/mandelbrot/assets/scss/components/_pen.scss
- packages/mandelbrot/assets/scss/core/_foundation.scss
- packages/mandelbrot/src/filters.js
- packages/mandelbrot/src/theme.js
- packages/mandelbrot/views/partials/stylesheets.nunj
Resolves #601.
Following this change, users will be able to customize Mandelbrot's sking with hex codes.
Previously we allowed specifying only the skin name:
```js
const mandelbrot = require('@frctl/mandelbrot')({
skin: 'fuchsia',
});
```
Now we will allow specifying an object with skin name and hex codes:
```js
const mandelbrot = require('@frctl/mandelbrot')({
skin: {
name: 'default',
accent: '#f2d',
complement: '#402',
links: '#a06',
},
});
```
We'll allow three colors - following the same naming convention in our skins definition. If the user's browser does not support CSS variables, it'll use the fallback color scheme (which defaults to default).
This will need documenting, once merged.
- I'm converting the user-specified hex codes into RGB for the CSS variables. This is so we could …
> feat: allow customizing skin with hex codes

- examples/handlebars/components/notes/notes.spec.js
- packages/fractal/src/api/variants/collection.js
⚠️ Branched from `examples`/#615, should be merged within or after.
Fixes #629
> fix: properly load notes from readme files for components variants

- packages/core/src/mixins/source.js
- packages/fractal/src/api/components/source.js
Fixes #660. 
This will increase file system parsing performance when there are huge amounts of excluded files and/or directories. For example. in my project (which is a monorepo where there are a lot of excluded node_modules dirs), I counted how many times the [build function](https://github.com/frctl/fractal/blob/main/packages/core/src/fs.js#L52) was called. Before this change, it was called 30412 times. After this change, only 2269 times. Time-wise it's something like 36s down to 6s. So it's pretty obvious how much perf this gives us, since Fractal parses the entire tree on every file change.
> feat: filter excluded files/directories in the file system parsing stage

- .gitattributes
- .github/workflows/release.yml
- package.json
- packages/core/package.json
- packages/handlebars/package.json
- packages/mandelbrot/package.json
- packages/nunjucks/package.json
- packages/twig/package.json
- packages/web/package.json
So this will:
- create a release through lerna with conventional commits (e.g. automatic versioning)
- push that release to the repository
- create a release on GitHub (yay!)
- publish the new versions/packages on npm
The workflow needs to be manually triggered on the repo.
I've validated that this workflow works [here](https://github.com/mihkeleidast/github-actions-lerna-publish-test), so fingers crossed this does not need some special config for a different repository.
> ci: automate release process

- .github/workflows/release.yml
This should resolve the issues I had this morning with the default token not being allowed to push to a protected branch.
> ci: make github actions use personal access token

- package-lock.json
- package.json
- packages/mandelbrot/assets/js/components/browser.js
- packages/mandelbrot/package.json
Closes #668
Select2 changed the way it detects modules starting 4.0.4, see [this comments thread](https://github.com/select2/select2/commit/45a877345482956021161203ac789c25f40a7d5e). Apparently it’s still not fixed in the latest version 4.0.13 so let’s go for the workaround.
FTR the regression on our side was introduced since [this commit](https://github.com/frctl/fractal/commit/e2fe7699dc47b1177894fc85c57f2e6d16fdf71f#diff-b3c812e431a045641b9e7129190c5ff4b31bab06bda461695572ad1e079b3f6eL55).
> fix(Mandelbrot): Properly initialize assets tab file select

- package-lock.json
- package.json
- packages/fractal/package.json
This resolves a deprecation warning users get when installing Fractal:
```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
└─┬ @frctl/fractal@1.4.1
└─┬ gray-matter@2.1.1
└── coffee-script@1.12.7
```
So small fix, it's been bugging me for years...
We have tests for yaml front matter in docs pages, so this should be good to go.
> build: update gray-matter

- packages/fractal/src/cli/commands/new.js
The default docs index file was renamed in https://github.com/frctl/fractal/commit/b23ecbaa433fb57fae20136ac7ea7e10469a34ff#diff-bce2cc04110d03fb1499379830faa44a173d254ad7f6f3fda808728746b291e5
The new command used the old `.hbs` file extension.
Fix #680
> fix: update file extension of docs index in new command

- packages/mandelbrot/assets/scss/components/_tree.scss
- packages/mandelbrot/src/theme.js
- packages/mandelbrot/views/partials/navigation/information.nunj
Resolves #624 and #647.
This will allow users to customize the information properties like this:
```
const mandelbrot = require('@frctl/mandelbrot');
fractal.web.theme(
mandelbrot({
information: [
{
label: 'version',
value: '1.2.3',
},
],
})
);
```
An information property's type can be set to `time` (defaults to `string`), in which case the property is marked up as `<time>` element.
Additionally, we provide an optional format prop if the base value needs to be formatted to a specific output - the usecase here is allowing to customize the date format, but I guess there could be other uses as well, if we should add other property types in the future.
This is the default:
```
fractal.web.theme(
mandelbrot({
information: [
{
label: 'Built on:',
value: new Date(),
type: 'time',
format: (value) …
```
> feat: allow custom information properties

- package-lock.json
- package.json
- packages/mandelbrot/package.json
Helps us analyze the bundle size on the go; previously it was necessary to always install the plugin temporarily.
> build: add webpack bundle analyzer

- package-lock.json
- package.json
- packages/mandelbrot/assets/js/components/browser.js
- packages/mandelbrot/assets/scss/components/_browser.scss
- packages/mandelbrot/assets/scss/components/_file-browser.scss
- packages/mandelbrot/package.json
Select2 is only used in a single place (assets file browser) in Mandelbrot, but accounts for ~30% of the JS bundle (did not analyze the CSS size, but I would presume the savings are also big). I know Mark had some additional ideas on how to use the Select2 dependency better but those never came to fruition.
> feat: style native select instead of using a plugin

- packages/mandelbrot/views/layouts/pen.nunj
- packages/mandelbrot/views/partials/pen/preview.nunj
When investigating performance issues, I discovered that even if I disable any additional panels (like 'html'), a component is still always rendered twice - once in the parent page that contains the iframe tag and then again inside the iframe.
Furthermore, the parent render's result actually seems to be discarded if the render is successful. If it fails, the render error is stored and rendered instead of the iframe. However, the same error would also be rendered inside the iframe if this feature were removed.
I dug around a bit and found that the render result was previously also used as the `srcdoc` attribute on the iframe.
Later, due to SVG rendering issues, [the srcdoc attribute was removed](https://github.com/frctl/mandelbrot/commit/8bdb9e92424ce43d12869ad61d60d33e313ae3ef), but the …
> perf: avoid extraneous render

- packages/mandelbrot/src/filters.js
If `item.references` is an empty array, an empty regex is created, which matches all empty strings between any two consecutive characters.
So if the input string contains `n` characters, the handle callback is invoked `n + 1` times.
As the parameter is an empty string, an error is thrown and caught each time.
I discovered this in a project where it added several seconds to the page render time.
This PR fixes the issue.
> fix: skip linkRefs if there are no references

- examples/handlebars/fractal.config.js
- examples/twig/fractal.config.js
The current syntax is wrong and doesn’t work. I also removed the panels list since it was the same as the default. Added a link to the available options instead. I know this basically does nothing but it’s useful when you want to quickly tweaks some Mandelbrot settings while working on or reviewing changes.
> chore(examples): use correct syntax to customize theme

- package-lock.json
- package.json
- packages/core/package.json
- packages/core/src/highlighter.js
- packages/mandelbrot/package.json
This resolves a nuisance that occurs when highlight.js is updated in the background. Highlight.js decided to log a deprecation message for every highlight call. See more in highlightjs/highlight.js#2277
> feat: update highlight.js

- package.json
- packages/mandelbrot/webpack.config.js
This fixes Mandelbrot theme build issue and adds the successful build requirement back to the test script.
> build: fix mandelbrot build

- packages/core/src/utils.js
- packages/core/test/utils.spec.js
This PR closes #1064.
It addresses the issue by using regex to find a file extension on the `toPath` when the path is found to start with a `.`.  The solution also incorporates a test to handle this edge case.
> fix: return correct relative path if preexisting file ext

- packages/core/src/utils.js
- packages/core/test/utils.spec.js
- The path generated to self will be emitted as ./self.ext
- This fixes an issue introduced by #1062
> fix: relative path generated to self

- packages/nunjucks/README.md
The code references .njk files but the associated code comment references .nunj files. 
Although there is no formal standard for Nunjuck file extensions, the community has largely opted to adopt .njk and it is the recommendation in the Nunjucks spec, so I assume that to be the "correct" option that is meant to be shown here.
> Fix typo in Nunjucks readme

- packages/core/src/mixins/entity.js
- packages/fractal/src/api/docs/doc.js
This is a minor change that, when generating labels for components, uses the original case version of `name` instead of the lowercased version. This means having component folder names like `someComponent/` correctly become `Some Component`, whereas without this change, it becomes `Somecomponent`.
> fix: don't lowercase name before titlizing to generate label

- examples/handlebars/components/one-very-very-long-component-name.hbs
- packages/mandelbrot/assets/scss/components/_tree.scss
> fix: wrap long text in navigation tree

- packages/mandelbrot/views/partials/header.nunj
Reported here: https://github.com/frctl/fractal-docs/issues/107#issuecomment-1026673252
Mistake on my part to not remove the visible text before merging.
> fix: remove printed out navigation type from header

- packages/mandelbrot/assets/js/components/search.js
Superseeding #1230 but without the recent cleanup so it can be released.
> fix: only expand tree's with matches
