frctl/fractal

docs/overview.md

Fix grammar in overview.md

---

package.json
src/web/server.js
test/support/env.js
views/cli/new/fractal.hbs

Windows compatibility fixes, including a fix for #88

Windows fixes

---

README.md

Add Link to GitHub profile of Paul Robert Lloyd

---

packages/internals/funjucks/README.md
packages/internals/funjucks/index.js
packages/internals/funjucks/index.test.js
packages/internals/funjucks/package.json
packages/internals/funjucks/src/env.js
packages/internals/funjucks/src/env.test.js
packages/internals/funjucks/src/filters/await.js
packages/internals/funjucks/src/filters/await.test.js
packages/internals/funjucks/src/filters/beautify.js
packages/internals/funjucks/src/filters/beautify.test.js
packages/internals/funjucks/src/filters/highlight.js
packages/internals/funjucks/src/filters/highlight.test.js
packages/internals/funjucks/src/filters/stringify.js
packages/internals/funjucks/src/filters/stringify.test.js
packages/internals/utils/src/utils.js
yarn.lock

This PR adds a new package to provide a customised, Fractal-specific Nunjucks environment for use in Fractal addons such as the inspector and static site builder.

Add custom Nunjucks environment for use in add-ons

---

package.json
packages/internals/support/index.js
packages/internals/support/index.test.js
packages/internals/support/package.json
packages/internals/support/src/collection.test.js
packages/internals/support/src/component-collection.js
packages/internals/support/src/component-collection.test.js
packages/internals/support/src/component.js
packages/internals/support/src/component.test.js
packages/internals/support/src/entity.js
packages/internals/support/src/entity.test.js
packages/internals/support/src/file-collection.js
packages/internals/support/src/file-collection.test.js
packages/internals/support/src/file.js
packages/internals/support/src/file.test.js
packages/internals/support/yarn.lock
yarn.lock

Migrates Component, ComponentCollection, and Entity classes, and tests for the index.
Adds skeleton support for File and FileCollection.

V2 internals supports

---

packages/toolkit/fractal/README.md
packages/toolkit/fractal/index.js
packages/toolkit/fractal/index.test.js
packages/toolkit/fractal/package.json
packages/toolkit/fractal/src/fractal.js
packages/toolkit/fractal/src/fractal.test.js

To help with the process of testing and building out of other related packages.

Add stub of main Fractal package

---

packages/internals/config/src/config.js
packages/internals/config/src/config.test.js

Fix to backwards accessor lookup logic 

---

packages/internals/support/src/emitting-promise.js
packages/internals/support/src/emitting-promise.test.js
yarn.lock

An implementation of the EmittingPromise, as discussed. 
**This PR can be for review purposes only.**

Review proposed version of EmittingPromise

---

packages/internals/config/index.js
packages/internals/config/index.test.js
packages/internals/config/src/accessors/extends-resolver.js
packages/internals/config/src/accessors/extends-resolver.test.js
packages/internals/config/src/accessors/package-loader.js
packages/internals/config/src/accessors/package-loader.test.js
packages/internals/config/src/accessors/packages-loader.js
packages/internals/config/src/config.js
packages/internals/config/src/config.test.js
packages/internals/config/src/extended-config.js
packages/internals/config/src/extended-config.test.js
packages/internals/utils/src/utils.js
packages/internals/utils/src/utils.test.js
packages/toolkit/fractal/src/config/init.js
packages/toolkit/fractal/src/config/init.test.js
packages/toolkit/fractal/src/config/schema.js
packages/toolkit/fractal/src/fractal.js
packages/toolkit/fractal/src/fractal.test.js
test/fixtures/add-ons/command.js
test/fixtures/add-ons/preset.js

Opening this PR to track progress on building out the Fractal core instance config handling logic.

[WIP] Implement config resolving, merging and validation

---

packages/add-ons/fractal-command-info/src/command.js
packages/internals/config/src/accessors/packages-loader.test.js
packages/internals/config/src/config.js
packages/internals/config/src/config.test.js
packages/internals/renderer/README.md
packages/internals/renderer/index.js
packages/internals/renderer/index.test.js
packages/internals/renderer/package.json
packages/internals/renderer/src/adapter-store.js
packages/internals/renderer/src/adapter-store.test.js
packages/internals/renderer/src/adapter.js
packages/internals/renderer/src/adapter.schema.js
packages/internals/renderer/src/adapter.test.js
packages/internals/renderer/src/renderer.js
packages/internals/renderer/src/renderer.test.js
packages/toolkit/fractal/package.json
packages/toolkit/fractal/src/config-store.js
packages/toolkit/fractal/src/config-store.test.js
packages/toolkit/fractal/src/config.schema.js
packages/toolkit/fractal/src/fractal.js
packages/toolkit/fractal/src/fractal.test.js
packages/toolkit/fractal/src/parser-cache.js
packages/toolkit/fractal/src/parser-cache.test.js
test/fixtures/add-ons/adapter.js

Note that `renderComponent` and `renderVariant` methods are just stubs right now. Also hooks the renderer up to the main Fractal instance.

Add basic renderer package

---

packages/toolkit/cli/bin/fractal
packages/toolkit/cli/package.json
packages/toolkit/cli/src/command-store.js
packages/toolkit/cli/src/command-store.test.js
packages/toolkit/cli/src/command.js
packages/toolkit/cli/src/command.schema.js
packages/toolkit/cli/src/command.test.js
yarn.lock

Introduces Command class wrapper for consistency with other add-ons, plus update-notification behaviour.

Minor CLI updates

---

packages/internals/support/src/emitting-promise.js
packages/internals/support/src/emitting-promise.test.js

@dkhuntrods so I think this works?? Test all pass and I can't think of any negative side affects. What do you think?

EmittingPromise: Pass entire emitter object to resolver

---

packages/fractal/fractal-transform-components/package.json
packages/fractal/fractal-transform-components/src/transform.js
packages/fractal/fractal-transform-components/src/transform.test.js

Complete implementation of fractal-transform-components module

---

packages/internals/support/src/entities/component.js
packages/internals/support/src/entities/component.test.js
packages/internals/support/src/entities/entity.js
packages/internals/support/src/entities/entity.test.js
packages/internals/utils/src/utils.js
packages/internals/utils/src/utils.test.js

Ran into a few issues with cloning components and with falsey props in the `.hash()` and `.toJSON()` methods. This PR adds tests for those cases and fixes the issues.

A few entity/component fixes

---

packages/fractal/fractal-transform-components/src/transform.js
packages/fractal/fractal-transform-components/src/transform.test.js
packages/fractal/fractal/src/fractal.js
packages/internals/config/src/config.js
packages/internals/support/src/collections/collection.js
packages/internals/support/src/collections/collection.test.js
packages/internals/support/src/collections/entity-collection.test.js
packages/internals/support/src/collections/variant-collection.js
packages/internals/support/src/collections/variant-collection.test.js
packages/internals/support/src/entities/component.js
packages/internals/support/src/entities/component.test.js
packages/internals/support/src/entities/entity.js
packages/internals/support/src/entities/variant.test.js
packages/internals/support/src/schema/variant.schema.js
packages/internals/utils/src/utils.js
packages/internals/utils/src/utils.test.js

Minor functionality changes for VariantCollection 
- make duplicate name incrementing consistent
- move responsibility for tracking from Component to VColl
- replace lodash.cloneDeep for utils.cloneDeep

V2 refactor variant collection

---

packages/internals/support/src/collections/collection.js
packages/internals/support/src/collections/collection.test.js
packages/internals/support/src/collections/component-collection.js
packages/internals/support/src/collections/entity-collection.js
packages/internals/support/src/collections/file-collection.js
packages/internals/support/src/collections/variant-collection.js

**NOTE** 
This PR doesn't merge into `v2`, but rather `v2-feature-entity-mapping`, so the order of merge is important!

Add explicit entity mapping

---

packages/internals/support/src/collections/file-collection.test.js
packages/internals/support/src/entities/component.js
packages/internals/support/src/entities/component.test.js

TODO: Testing of integration with global config

Implement component.getView() and .getViews()

---

packages/fractal/fractal-preset-core/package.json
packages/fractal/fractal-preset-core/src/preset.js
packages/fractal/fractal/package.json
packages/fractal/fractal/src/config/defaults.js
packages/fractal/fractal/src/config/store.js
packages/fractal/fractal/src/fractal.test.js

Small PR implementing improvement discussed with @dkhuntrods

Include component transform directly in Fractal core

---

package-lock.json

The Snyk PR is failing, and I can't get into Snyk to do anything about it :( This PR just applies security updates to Lodash.

Update Lodash to 4.17.14

---

src/core/adapter.js
src/web/server.js

#526: Regex escaping

---

src/core/fs.js
src/core/mixins/source.js

fix entity names with double extension

---

package-lock.json
package.json
test/core.mixins.collection.js

I'm trying to up my test writing skill and this project needs some tests, so here's a first draft.
Coverage-wise the situation is a bit better than it was before, although I'm not really sure how relevant all those tests are. I guess there could be more expects here and there, suggestions are welcome.
Skipped squash method in that mixin class, since I couldn't really figure out the expectations for that - as far as I looked, it isn't documented nor used anywhere. Wondering if we could mark it as deprecated and/or remove immediately...

add coverage and unit tests for collection mixin class

---

.github/ISSUE_TEMPLATE.md
README.md
bin/fractal
src/cli/commands/new.js

allow and prefer fractal.config.js as configuration file name

---

package-lock.json
package.json
src/cli/commands/new.js
src/core/shell.js
test/core.shell.js

Fixes #550 
I decided to open a PR because it works like that but I have no clue if this is actually a good solution 😂 
@Chapabu would definitely need your input on that, apparently you worked on this part when removing shelljs a while ago.

fix(CLI): ensure new command runs npm install

---

package-lock.json
package.json
packages/fractal/package.json
packages/fractal/src/cli/commands/new.js
packages/fractal/src/web/builder.js

refactor: update fs-extra

---

README.md

This issue was resolved in #581 so it should not be necessary to point it out anymore.

docs: remove note for windows

---

packages/fractal/CHANGELOG.md
packages/handlebars/CHANGELOG.md
packages/mandelbrot/CHANGELOG.md
packages/nunjucks/CHANGELOG.md
packages/twig/CHANGELOG.md

docs: complete Changelogs with missing versions

---

packages/mandelbrot/README.md

fixes #609
Should be merged after #615 as it references it.

docs: document how to work on Mandelbrot

---

examples/handlebars/components/collated/__snapshots__/collated.spec.js.snap
examples/handlebars/components/collated/collated.config.js
examples/handlebars/components/collated/collated.hbs
examples/handlebars/components/collated/collated.spec.js
examples/handlebars/fractal.config.js
packages/mandelbrot/src/theme.js
packages/mandelbrot/views/partials/browser/controls.nunj
packages/mandelbrot/views/partials/browser/panel-context.nunj
packages/mandelbrot/views/partials/browser/panel-info.nunj
packages/mandelbrot/views/partials/browser/panel-notes.nunj
packages/mandelbrot/views/partials/browser/panel-resources.nunj
packages/mandelbrot/views/partials/pen/header.nunj

feat(Mandelbrot): allow to customize all the theme labels

---

examples/handlebars/components/render-tag/comp-1.config.yml
examples/handlebars/components/render-tag/comp-1.hbs
examples/handlebars/components/render-tag/comp-2.config.yml
examples/handlebars/components/render-tag/comp-2.hbs
examples/handlebars/components/render-tag/config.yml
examples/handlebars/components/render-tag/render-tag.spec.js
packages/handlebars/src/helpers/render.js

fix(handlebars): fix render tag overwriting default context

---

packages/mandelbrot/views/partials/browser/panel-info.nunj

fix(mandelbrot): hide hidden variants in info panel

---

package-lock.json
package.json

Resolves a security vulnerability dependabot can't fix on it's own.

build: update lerna and dot-prop

---

examples/handlebars/components/components.spec.js
examples/handlebars/components/render/render--camelCaseVariant.hbs
examples/handlebars/components/render/render--variant-2.hbs
examples/handlebars/components/render/render.config.yml
examples/handlebars/components/render/render.spec.js
packages/fractal/src/api/variants/collection.js

fix(fractal): fix resolving camelCased variant templates

---

packages/mandelbrot/assets/js/mandelbrot.js

fix: initialize frame before navigation

---

packages/mandelbrot/assets/js/components/search.js

feat: focus search input after clearing it

---

package-lock.json
package.json
packages/web/package.json

This will resolve a security vulnerability in a browser-sync dependency.

build: update browser-sync

---

examples/handlebars/components/root/root-tree/root-tree-leaf.hbs
examples/handlebars/components/root/root.config.yml
packages/core/src/entities/collection.js
packages/core/src/mixins/collection.js
packages/fractal/src/api/components/source.js
packages/mandelbrot/views/macros/navigation.nunj
packages/mandelbrot/views/partials/navigation/components.nunj

feat: allow pulling collections to root

---

.github/CODE_OF_CONDUCT.md

Change Danielle's email address to Matt's

docs: Update email address in code of conduct

---

examples/handlebars/components/partial-block/config.yml
examples/handlebars/components/partial-block/parent.hbs
examples/handlebars/components/partial-block/partial-block.spec.js
examples/handlebars/components/partial-block/partial.hbs
packages/handlebars/src/adapter.js

fix: clone only data for mutations

---

packages/fractal/bin/fractal.js

refactor: fix typo in update-notifier require name

---

.github/workflows/test.yml

I’ve already updated the settings to not require macOS to pass to be able to merge.

chore(ci): remove macOS

---

examples/react/components/_preview.jsx
examples/react/components/context/__snapshots__/context.spec.js.snap
examples/react/components/render/__snapshots__/render.spec.js.snap
examples/react/fractal.config.js
packages/fractal/src/api/components/source.js

fix: try to resolve file preview to a component

---

packages/handlebars/package.json

How has this been working at all...

fix(handlebars): fix main file path

---

packages/react/src/clear-module.js

fix(react): fix infinite loop when checking for module dependent paths

---

README.md
packages/fractal/README.md
packages/fractal/package.json

docs: remove ambiquity in descriptions

---

packages/core/src/mixins/source.js

fix: sync for docs
